import type { NextPage } from "next";
import Head from "next/head";
import useAuth from "../hooks/useAuth";

const Home: NextPage = () => {
  const { logOut } = useAuth();

  return (
    <div>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-3xl font-bold underline">hi</h1>

        <button onClick={logOut} className="border">
          Logout
        </button>
      </div>
    </div>
  );
};

export default Home;
