import { collection, getDocs, getFirestore } from "firebase/firestore";
import type { NextPage } from "next";
import Head from "next/head";
import { auth, db } from "../firebase.config";
import useAuth from "../hooks/useAuth";
import { useCollection } from "react-firebase-hooks/firestore";
import React from "react";

const Home: NextPage = () => {
  const { logOut } = useAuth();
  const user = auth.currentUser;
  // use update updateProfile() to update. pin any new methodes if found.

  // const querySnapshot = await getDocs(collection(db, "users"));
  // querySnapshot.forEach((doc) => {
  //   console.log(`${doc.id} => ${doc.data()}`);
  // });

  const [todos, todosLoading, todoserror] = useCollection(
    collection(getFirestore(), "Todos"),
    { snapshotListenOptions: { includeMetadataChanges: true } }
  );

  return (
    <div>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-3xl font-bold underline">hi</h1>
        <p className="text-2xl">{user?.displayName}</p>
        <p>{user?.email}</p>
        <p>
          {todoserror && <strong>Error: {JSON.stringify(todoserror)}</strong>}
          {todosLoading && <span>Collection: Loading...</span>}
          {todos && (
            <span>
              Collection:{" "}
              <ul>
                {todos.docs.map((doc) => (
                  <li key={doc.id}>{JSON.stringify(doc.data().todo)}, </li>
                ))}
              </ul>
            </span>
          )}
        </p>

        <button onClick={logOut} className="border">
          Logout
        </button>
      </div>
    </div>
  );
};

export default Home;
