import Head from "next/head";
import React from "react";

export default function login() {
  return (
    <div>
      <Head>
        <title>Todo App | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-center">
        <div>Login Page</div>
      </div>
    </div>
  );
}
