import Head from "next/head";
import { useState } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import useAuth from "../hooks/useAuth";

interface Inputs {
  email: string;
  password: string;
}

const Login = () => {
  const [login, setLogin] = useState(false);
  const { signIn, signUp } = useAuth();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = async ({ email, password }) => {
    if (login) {
      await signIn(email, password);
    } else {
      await signUp(email, password);
    }
  };

  return (
    <div className="">
      <Head>
        <title>TodoApp | SignIn</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit(onSubmit)} className="">
        <h1>Sign In</h1>
        <div className="">
          <label className="">
            <input
              type="email"
              placeholder="Email"
              className=""
              {...register("email", { required: true })}
            />
            {errors.email && (
              <p className="p-1 text-[13px] font-light  text-orange-500">
                Please enter a valid email.
              </p>
            )}
          </label>
          <label className="">
            <input
              type="password"
              placeholder="Password"
              className=""
              {...register("password", { required: true })}
            />
            {errors.password && (
              <p className="">
                Your password must contain between 4 and 60 characters.
              </p>
            )}
          </label>
        </div>

        <button type="submit" className="" onClick={() => setLogin(true)}>
          Sign In
        </button>
        <div className="">
          New to Netflix?{" "}
          <button type="submit" className="" onClick={() => setLogin(false)}>
            Sign up now
          </button>
        </div>
      </form>
    </div>
  );
};

export default Login;

// work on making 2 different forms for login and signup!
// import Head from "next/head";
// import { type } from "os";
// import { useForm, SubmitHandler } from "react-hook-form";
// import useAuth from "../hooks/useAuth";

// type InputsSignUp = {
//   emailSignUp: string;
//   passwordSignUp: string;
//   passwordConfirmSignUp: string;
// };

// type InputsSignIn = {
//   emailSignIn: string;
//   passwordSignIn: string;
// };

// export default function signup() {
//   const { signUp, signIn } = useAuth();

//   const {
//     registerSignUp,
//     handleSubmitSignUp,
//     formState: { errors },
//   } = useForm<InputsSignUp>();

//   const {
//     register,
//     handleSubmit,
//     formState: { errors },
//   } = useForm<InputsSignUp>();

//   const onSubmitSignUp: SubmitHandler<InputsSignUp> = async ({
//     emailSignUp,
//     passwordSignUp,
//     passwordConfirmSignUp,
//   }) => {
//     console.log(emailSignUp);
//     if (passwordSignUp === passwordConfirmSignUp) {
//       console.log(passwordSignUp);
//       // import signup hook here...
//       await signUp(emailSignUp, passwordSignUp);
//     }
//   };

//   const onSubmitLogin: SubmitHandler<InputsSignIn> = async ({
//     emailSignIn,
//     passwordSignIn,
//   }) => {
//     console.log(emailSignIn);
//     console.log(passwordSignIn);
//     // import signup hook here...
//     await signIn(emailSignIn, passwordSignIn);
//   };

//   return (
//     <div>
//       <Head>
//         <title>Todo App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div>
//         <h2>Login</h2>
//         <form onSubmit={handleSubmit(onSubmitLogin)}>
//           {/* remove border class from input to  update design */}
//           <div>
//             <label>Email</label>
//             <input
//               className="border"
//               type="text"
//               {...register("emailSignIn", { required: true })}
//             />
//             {errors.emailSignUp && <p>Email is required.</p>}
//           </div>
//           <div>
//             <label>Password</label>
//             <input
//               className="border"
//               type="password"
//               {...register("passwordSignIn", { required: true })}
//             />
//             {errors.emailSignIn && <p>Password is required.</p>}
//           </div>
//           <button className="border" type="submit">
//             Login
//           </button>
//         </form>
//       </div>

//       {/*  */}
//       <div>
//         <h2>Sign Up</h2>
//         <form onSubmit={handleSubmit(onSubmitSignUp)}>
//           {/* remove border class from input to  update design */}
//           <div>
//             <label>Email</label>
//             <input
//               className="border"
//               type="text"
//               {...registerSignUp("emailSignUp", { required: true })}
//             />
//             {errors.emailSignUp && <p>Email is required.</p>}
//           </div>
//           <div>
//             <label>Password</label>
//             <input
//               className="border"
//               type="password"
//               {...registerSignUp("passwordSignUp", { required: true })}
//             />
//             {errors.passwordSignUp && <p>Password is required.</p>}
//           </div>
//           <div>
//             <label>Password Confirm</label>
//             <input
//               className="border"
//               type="password"
//               required
//               {...registerSignUp("passwordConfirmSignUp", { required: true })}
//             />
//             {errors.passwordConfirmSignUp && <p>Retype password is required.</p>}
//           </div>
//           <button className="border" type="submit">
//             Sign Up
//           </button>
//         </form>
//       </div>
//     </div>
//   );
// }
